# Makefile
# Chris Schultz
# 30 May 2020
#
# Makefile for Hello Triangle program
CXX=g++
CXXFLAGS=-std=c++11
RM=/bin/rm -f

hellotriangle: main.cpp
	${CXX} ${CXXFLAGS} -o hellotriangle main.cpp

clean:
	${RM} hellotriangle
